services:
  # Backend API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./api:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    networks:
      - video-library

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - NEXT_DOCKER_API_URL=http://host.docker.internal:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - video-library
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sqlite_data:

networks:
  video-library:
    driver: bridge 